spring:
  application:
    name: ws-bccmusic-api

  datasource:
    url: jdbc:sqlserver://192.168.0.10:1433;databaseName=BCCMusic;encrypt=true;trustServerCertificate=true;
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  security:
    web:
      firewall: 
        http-firewall: org.springframework.security.web.firewall.StrictHttpFirewall
        strict-http:firewall: false
    password:
      bcrypt-strength: 12

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    ldap:
      enabled: false

server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
    # cc.kercheval: DEBUG   # Uncomment when debugging your own code